Month 7/step 2
Zorkiy82/react-burger pull request #3
Opened 2022-08-14 11:53 UTC by Zorkiy82

Month 7/step 2

2022-08-15 06:32 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавить проверку успешности запроса
- Перенести `modal-overlay` в компонент модалки
- Добавить propTypes всем компонентам с пропсами
- Переделать `modal-overlay` и `modal`.

Более подробно описание проблемы смотрите комментарии в pull request.

Что понравилось:
- Используете константу для url адреса 
- Правильно типизировали поля ингредиента
- Код написан аккуратно, легко читать
- Используете отписку от слушателя

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2022-08-15 06:32 UTC, andryxxa93 commented on src/app.js
> +      .then((data) => {
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2022-08-15 06:32 UTC, andryxxa93 commented on src/app.js
> +        alert(err);
**Можно лучше**
`Alert` обычно не принято использовать для оповещения пользователя. Для этого больше подходит модальное окно которое уже есть в проекте.

2022-08-15 06:32 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +    <ModalOverlay onClose={handleCloseModal}>
**Необходимо исправит**
Не нужно оборачивать каждый вызов модалки в `modal-overlay`. Достаточно один раз вызвать её внутри компонента модалки. И к тому же у `modal-overlay` не должно быть детей, это просто подложка.

2022-08-15 06:32 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +function BurgerConstructor(props) {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2022-08-15 06:32 UTC, andryxxa93 commented on src/components/constructor-card/constructor-card.js
> +function ConstructorCard(props) {
**Необходимо исправить**
Все компоненты с пропсами должны иметь propTypes

2022-08-15 06:32 UTC, andryxxa93 commented on src/components/ingredients-list/ingredients-list.js
> +          key={index}
**Можно улучшить**
В качестве key не следует использовать index. Лучше использовать уникальный _id, который есть у каждой карточки
https://ru.reactjs.org/docs/lists-and-keys.html#gatsby-focus-wrapper

2022-08-15 06:32 UTC, andryxxa93 commented on src/components/modal-overlay/modal-overlay.js
> +  }
**Необходимо исправить**
Всё содержимое этого компонента на самом деле должно быть внутри компонента `modal`. Modal-overlay это просто подложка. Она ничего не принимает и не содержит никакой логики, а просто отображает задний черный фон, кстати который не отображается у вас в проекте, это тоже нужно исправить.

2022-08-15 16:37 UTC, Zorkiy82 commented on src/app.js
> +      .then((data) => {
Выполнено

2022-08-15 16:38 UTC, Zorkiy82 commented on src/app.js
> +        alert(err);
Выполнено

2022-08-15 17:53 UTC, Zorkiy82 commented on src/components/burger-constructor/burger-constructor.js
> +    <ModalOverlay onClose={handleCloseModal}>
Выполнено

2022-08-15 17:57 UTC, Zorkiy82 commented on src/components/ingredients-list/ingredients-list.js
> +          key={index}
Выполнено

2022-08-15 17:57 UTC, Zorkiy82 commented on src/components/modal-overlay/modal-overlay.js
> +  }
Выполнено

2022-08-15 18:53 UTC, Zorkiy82 commented on src/components/constructor-card/constructor-card.js
> +function ConstructorCard(props) {
Выполнено

2022-08-16 10:17 UTC, andryxxa93 requested changes
Всё отлично! Единственный момент - сделайте так, чтобы подписка на прослушиватель события происходила только один раз при первом рендере и ваша работа будет принята.

2022-08-16 10:17 UTC, andryxxa93 commented on src/app.js
> +
**Можно лучше**
Это всё можно перенести в отдельную директорию `burger-api`. Просто в будущем количество запросов увеличится и чтобы не дублировать код лучше перенести.

2022-08-16 10:17 UTC, andryxxa93 commented on src/app.js
>      fetch(ApiUrl)
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-08-16 10:17 UTC, andryxxa93 commented on src/components/modal/modal.js
> +  React.useEffect(() => {
**Необходимо исправить**
Необходимо чтобы подписка на прослушиватель события происходила только один раз, сейчас она будет происходить каждый перерендер компонента.

2022-08-16 14:29 UTC, Zorkiy82 commented on src/components/modal/modal.js
> +  React.useEffect(() => {
Выполнено

2022-08-16 15:33 UTC, Zorkiy82 commented on src/app.js
>      fetch(ApiUrl)
Выполнено

2022-08-16 15:33 UTC, Zorkiy82 commented on src/app.js
> +
Выполнено

2022-08-16 18:33 UTC, andryxxa93 approved these changes
Отлично! Ваша работа принята. Удачного продолжения обучения!

2022-08-16 18:56 UTC, merged